variables:
  # Skip building on Python 2.7 on all platforms
  CIBW_SKIP: cp27-*
  CIBW_BEFORE_BUILD: "pip install -r requirements.txt"
  # https://github.com/matthew-brett/delocate/pull/39
  CIBW_BEFORE_BUILD_MACOS: "pip install -r requirements.txt && pip install git+https://github.com/matthew-brett/delocate.git@single-file-refactor"
  CIBW_BEFORE_BUILD_LINUX: "pip install -r requirements.txt && bash ci/centos_install_libarchive_builddep.sh && bash ci/build_libarchive.sh"
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: "pytest {project}/tests"
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  - job: test
    variables:
      LD_LIBRARY_PATH: /usr/local/lib
    steps:
      - bash: bash ci/download_libarchive.sh
        displayName: download libarchive
      - bash: |
          sudo apt update
          sudo apt install -y build-essential cmake libssl-dev libacl1-dev libbz2-dev liblzma-dev libzip-dev liblz4-dev libzstd-dev lzop
        displayName: install build dependencies for libarchive
      - bash: sudo bash ci/build_libarchive.sh
        displayName: build libarchive
      - task: UsePythonVersion@0
      - bash: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r dev-requirements.txt
          python setup.py test
      - bash: |
          bash <(curl -s https://codecov.io/bash)
        displayName: "Upload to codecov.io"
  - job: linux_wheels
    pool: { vmImage: "Ubuntu-16.04" }
    steps:
      - bash: bash ci/download_libarchive.sh
        displayName: download libarchive
      - task: UsePythonVersion@0
      - bash: |
          python -m pip install --upgrade pip setuptools wheel twine
          pip install cibuildwheel==1.0.0
          cibuildwheel --output-dir wheelhouse .
          twine check wheelhouse/*.whl
      - task: PublishBuildArtifacts@1
        inputs: { pathtoPublish: "wheelhouse" }
  - job: macos_wheels
    pool: { vmImage: "macOS-10.13" }
    variables:
      LDFLAGS: "-L/usr/local/opt/libarchive/lib"
      CPPFLAGS: "-I/usr/local/opt/libarchive/include"
      PKG_CONFIG_PATH: "/usr/local/opt/libarchive/lib/pkgconfig"
    steps:
      - bash: brew install libarchive
        displayName: Install libarchive
      - task: UsePythonVersion@0
      - bash: |
          python -m pip install --upgrade pip setuptools wheel
          pip install cibuildwheel==1.0.0
          cibuildwheel --output-dir wheelhouse .
      - task: PublishBuildArtifacts@1
        inputs: { pathtoPublish: "wheelhouse" }
  - job: windows_wheels
    pool: { vmImage: "vs2017-win2016" }
    variables:
      USE_LIBARCHIVE_FROM_PROGRAM_FILES: "true"
    steps:
      - bash: bash ci/download_libarchive.sh
        displayName: download libarchive
      - script: ci/build_libarchive.cmd
        displayName: build libarchive
      - task: UsePythonVersion@0
      - script: |
          DIR "C:\Program Files (x86)\libarchive\lib"
          DIR "C:\Program Files (x86)\libarchive\include"
          SET PATH="C:\Program Files (x86)\libarchive\lib";%PATH%
          python -m pip install --upgrade pip
          pip install cibuildwheel==1.0.0
          cibuildwheel --output-dir wheelhouse .
      - task: PublishBuildArtifacts@1
        inputs: { pathtoPublish: "wheelhouse" }
